baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "github.com/themefisher/northendlab-hugo"
title = "elair services "
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Elair"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "Agence web"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/logo.SVG"
social = []
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/Hom.jpg"
title = ""
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
<script async src='https://stackwhats.com/pixel/334e30305da5ad40336f5635b67bb1'></script>
